### ISSUE TITLE
[Legacy Branch] Window Transparency only works on one monitor

### ISSUE THREAD

**Issue by umbreonben** [ALTaleX531/OpenGlass#23] opened 2024-08-16 09:59 UTC
I have 2 monitors and on my second one the transparency is working properly and on the other one it's just black without any transparency. When a notification pops up on the first monitor it suddenly works, but as soon as the notification goes away the transparency is gone again.

Monitor 1:
![image](https://github.com/user-attachments/assets/20814d44-7db2-4a23-98a1-fb33df2fbb76)

Monitor 2:
![image](https://github.com/user-attachments/assets/ca239d2e-5cef-47f1-96d3-db0d33620763)

**Comment by ALTaleX531** [comment] 2024-08-16 10:08
Duplicate of #15.

**Closed by ALTaleX531** 2024-08-16 10:08 UTC
Labels: bug, duplicate, branch: legacy

**Comment by ALTaleX531** [comment] 2024-08-16 10:09
For multiple monitors, use the master branch instead of the legacy branch.
