### ISSUE TITLE
[Legacy Branch] Window Colors/Transparency only works on one monitor

### ISSUE THREAD

**Issue by umbreonben** [ALTaleX531/OpenGlass#25] opened 2024-08-20 10:35 UTC
I have 2 monitors and on my second one the transparency and the custom set color is working properly and on the other one it's just black without any transparency. When a notification pops up on the first monitor it suddenly works, but as soon as the notification goes away the transparency and color is gone again.

First Monitor:
![image](https://github.com/user-attachments/assets/05b0cb14-176e-4305-a69c-043343a8e54f)

Second Monitor:
![image](https://github.com/user-attachments/assets/524cc1f4-faf0-4d6a-86cd-4b9c99f3d389)

**Comment by ALTaleX531** [comment] 2024-08-20 11:26
Duplicate of #23.
I don't understand why you posted it again.

**Closed by ALTaleX531** 2024-08-20 11:26 UTC

**Comment by umbreonben** [comment] 2024-08-23 13:54
Sorry, it was a weird github bug where my issue was completly gone, so I decided to post it again. now both are up and I just look like a fool now
